# An implementation of sequence to sequence learning for performing addition

Input: "535+61"
Output: "596"
Padding is handled by using a repeated sentinel character (space)

Input may optionally be reversed, shown to increase performance in many tasks in:
"Learning to Execute"
http://arxiv.org/abs/1410.4615
and
"Sequence to Sequence Learning with Neural Networks"
http://papers.nips.cc/paper/5346-sequence-to-sequence-learning-with-neural-networks.pdf
Theoretically it introduces shorter term dependencies between source and target.

Two digits reversed:
+ One layer LSTM (128 HN), 5k training examples = 99% train/test accuracy in 55 epochs

Three digits reversed:
+ One layer LSTM (128 HN), 50k training examples = 99% train/test accuracy in 100 epochs

Four digits reversed:
+ One layer LSTM (128 HN), 400k training examples = 99% train/test accuracy in 20 epochs

Five digits reversed:
+ One layer LSTM (128 HN), 550k training examples = 99% train/test accuracy in 30 epochs

In [ ]:
import numpy as np
from six.moves import range
import sys

In [ ]:
import keras as K
import tensorflow as tf
from keras.models import Sequential
from keras import layers

# config = tf.ConfigProto( device_count = {'GPU': 1 , 'CPU': 56} ) 
config = tf.ConfigProto(device_count = {'GPU': 1 , 'CPU': 8} ) 
config.gpu_options.allow_growth = True # toma memoria poco a poco según le haga falta

sess = tf.Session(config=config) 
K.backend.set_session(sess)

Using TensorFlow backend.


In [ ]:
class CharacterTable(object):
    """Given a set of characters:
    + Encode them to a one-hot integer representation
    + Decode the one-hot or integer representation to their character output
    + Decode a vector of probabilities to their character output
    """
    def __init__(self, chars):
        """Initialize character table.

        # Arguments
            chars: Characters that can appear in the input.
        """
        self.chars = sorted(set(chars))
        self.char_indices = dict((c, i) for i, c in enumerate(self.chars))
        self.indices_char = dict((i, c) for i, c in enumerate(self.chars))

    def encode(self, C, num_rows):
        """One-hot encode given string C.

        # Arguments
            C: string, to be encoded.
            num_rows: Number of rows in the returned one-hot encoding. This is
                used to keep the # of rows for each data the same.
        """
        x = np.zeros((num_rows, len(self.chars)))
        for i, c in enumerate(C):
            x[i, self.char_indices[c]] = 1
        return x

    def decode(self, x, calc_argmax=True):
        """Decode the given vector or 2D array to their character output.

        # Arguments
            x: A vector or a 2D array of probabilities or one-hot representations;
                or a vector of character indices (used with `calc_argmax=False`).
            calc_argmax: Whether to find the character index with maximum
                probability, defaults to `True`.
        """
        if calc_argmax:
            x = x.argmax(axis=-1)
        return ''.join(self.indices_char[x] for x in x)

In [ ]:
# All the numbers, plus sign and space for padding.
chars = '0123456789+ ' # simple vocabulary
ctable = CharacterTable(chars)

In [ ]:
ctable.encode(C='0 +', num_rows=10)

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
x = ctable.encode(C='0 +', num_rows=5)
print(x)
ctable.decode(x)

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


'0 +  '

In [ ]:
class colors:
    ok = '\033[92m'
    fail = '\033[91m'
    close = '\033[0m'

In [ ]:
# generamos el dataset de preguntas y respuestas para un numero de digitos de sumando igual
# cuidando que no se repitan preguntas
def generate_training(TRAINING_SIZE = 50000, DIGITS = 3, REVERSE = True):

    # Maximum length of input is 'int + int' (e.g., '345+678'). Maximum length of
    # int is DIGITS.
    MAXLEN = DIGITS + 1 + DIGITS

    questions = []
    answers = []
    seen = set()
    print('Generating data...')
    while len(questions) < TRAINING_SIZE:
        f = lambda: int(''.join(np.random.choice(list('0123456789'))
                        for i in range(np.random.randint(1, DIGITS + 1))))
        a, b = f(), f()
        # Skip any addition questions we've already seen
        # Also skip any such that x+Y == Y+x (hence the sorting).
        key = tuple(sorted((a, b))) # ordenamos para tener en cuenta la propiedad conmutativa de la suma
        if key in seen:
            continue
        seen.add(key)
        # Pad the data with spaces such that it is always MAXLEN.
        q = '{}+{}'.format(a, b)
        query = q + ' ' * (MAXLEN - len(q))
        ans = str(a + b)
        # Answers can be of maximum size DIGITS + 1.
        ans += ' ' * (DIGITS + 1 - len(ans))
        if REVERSE:
            # Reverse the query, e.g., '12+345  ' becomes '  543+21'. (Note the
            # space used for padding.)
            query = query[::-1]
        questions.append(query)
        answers.append(ans)
    print('Total addition questions:', len(questions))
    out = np.vstack((np.array(questions), np.array(answers)))
    return out.T

In [ ]:
generate_training(5,1,False)

Generating data...
Total addition questions: 5


array([['6+9', '15'],
       ['4+3', '7 '],
       ['6+1', '7 '],
       ['9+8', '17'],
       ['8+4', '12']], dtype='<U3')

In [ ]:
train3char = generate_training(TRAINING_SIZE=50000, DIGITS=3, REVERSE=False)

Generating data...
Total addition questions: 50000


In [ ]:
train3char.shape

(50000, 2)

In [ ]:
train3char

array([['525+841', '1366'],
       ['816+883', '1699'],
       ['17+5   ', '22  '],
       ...,
       ['210+943', '1153'],
       ['40+995 ', '1035'],
       ['278+85 ', '363 ']], dtype='<U7')

In [ ]:
r = np.random.randint(low=0, high=train3char.shape[0], size=4)
train3char[r, :]

array([['70+88  ', '158 '],
       ['814+141', '955 '],
       ['147+580', '727 '],
       ['229+5  ', '234 ']], dtype='<U7')

In [ ]:
# aplicamos one-hot
def vectorization(train, DIGITS):
    MAXLEN = 2*DIGITS+1
    print('Vectorization...')
    # samples, estados (long secuencia), dim embedding
    x = np.zeros((train.shape[0], MAXLEN, len(chars)), dtype=np.bool)
    y = np.zeros((train.shape[0], DIGITS + 1, len(chars)), dtype=np.bool)
    # encode questions
    for i, sentence in enumerate(train[:, 0]):
        x[i] = ctable.encode(sentence, MAXLEN)
    # encode answers
    for i, sentence in enumerate(train[:, 1]):
        y[i] = ctable.encode(sentence, DIGITS + 1)

    # Shuffle (x, y) in unison as the later parts of x will almost all be larger
    # digits.
    indices = np.arange(len(y))
    np.random.shuffle(indices)
    x = x[indices]
    y = y[indices]

    # Explicitly set apart 10% for validation data that we never train over.
    split_at = len(x) - len(x) // 10
    (x_train, x_val) = x[:split_at], x[split_at:]
    (y_train, y_val) = y[:split_at], y[split_at:]

    print('Shapes in training Data:')
    print(x_train.shape)
    print(y_train.shape)

    print('Shapes in validation Data:')
    print(x_val.shape)
    print(y_val.shape)
    return x_train, y_train, x_val, y_val

In [ ]:
x_train_3char, y_train_3char, x_val_3char, y_val_3char = vectorization(train=train3char, DIGITS=3)

Vectorization...
Shapes in training Data:
(45000, 7, 12)
(45000, 4, 12)
Shapes in validation Data:
(5000, 7, 12)
(5000, 4, 12)


In [ ]:
def build_model(chars, rnn_type='gru', DIGITS=3, HIDDEN_SIZE=10, BATCH_SIZE=100, DECODER_LAYERS=1):
    # ...
    MAXLEN = 2*DIGITS + 1
    
    if rnn_type == 'gru':
        RNN = layers.GRU
    elif rnn_type == 'lstm':
      RNN = layers.LSTM
    elif rnn_type == 'rnn':
      RNN = layers.simpleRNN
    else:
      sys.exit(-1)

    
    m = Sequential()
    m.add(RNN(HIDDEN_SIZE, input_shape=(MAXLEN, len(chars)))) 
    m.add(layers.RepeatVector(DIGITS + 1)) # replicamos la salida de la capa recurrente para meterla en el siguiente paso (decodificador), donde aprenderá la salida
    #decoder
    m.add(RNN(HIDDEN_SIZE, return_sequences=True))
    # Aplicamos la misma capa densa a todos los estados de salida de la anterior
    # Densa que saque la salida en forma de one-hot
    m.add(layers.TimeDistributed(layers.Dense(len(chars), activation = 'softmax'))) # el tamaño de salida es el que necesita el decodificador
    m.compile(loss = 'categorical_crossentropy', optimizer='adam', metrics=['accuracy'])  
    m.summary()
    return m

In [ ]:
model3char = build_model(chars=chars, rnn_type='lstm', DIGITS=3, HIDDEN_SIZE=128, BATCH_SIZE=128, DECODER_LAYERS=1)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_3 (LSTM)                (None, 128)               72192     
_________________________________________________________________
repeat_vector_2 (RepeatVecto (None, 4, 128)            0         
_________________________________________________________________
lstm_4 (LSTM)                (None, 4, 128)            131584    
_________________________________________________________________
time_distributed_2 (TimeDist (None, 4, 12)             1548      
Total params: 205,324
Trainable params: 205,324
Non-trainable params: 0
_________________________________________________________________


In [ ]:
def train(model, x_train, y_train, x_val, y_val,  n_epochs=20, BATCH_SIZE=128, REVERSE=False):
    # Train the model each generation and show predictions against the validation
    # dataset.
    for iteration in range(1, n_epochs+1):
        print()
        print("-"*50)
        print("Iteration", iteration)
        
        # Train
        model.fit(x_train, y_train, epochs = 1, batch_size = 256, validation_data = (x_val, y_val))
        
        # Select 5 samples from the validation set at random so we can visualize
        # errors.
        idx_val = np.random.randint(0, len(x_val), 5)
        pred = model.predict(x_val[idx_val])
        for i in range(5):
          #idx_val = np.array(np.random.randint(0, len(x_val)))
          #print(idx_val, np.array(idx_val))
          
          
          
          
          p = ctable.decode(x_val[idx_val[i]])
          correct = ctable.decode(y_val[idx_val[i]])
          guess = ctable.decode(pred[i])
          
          print('Question: ', p, 'Answer: ', correct)
          
          if correct == guess:
              print(colors.ok + '☑' + colors.close, end=' ')
          else:
              print(colors.fail + '☒' + colors.close, end=' ')
          print('Guess: ', guess, end='\n')

In [ ]:
train(model3char, x_train_3char, y_train_3char, x_val_3char, y_val_3char,  n_epochs=100, 
      BATCH_SIZE=128, REVERSE=False)


--------------------------------------------------
Iteration 1
Train on 45000 samples, validate on 5000 samples
Epoch 1/1
45000/45000 [==============================] - 6s 140us/step - loss: 0.0156 - acc: 0.9986 - val_loss: 0.0302 - val_acc: 0.9915
Question:  146+21  Answer:  167 
☑ Guess:  167 
Question:  416+108 Answer:  524 
☑ Guess:  524 
Question:  91+81   Answer:  172 
☑ Guess:  172 
Question:  49+949  Answer:  998 
☑ Guess:  998 
Question:  950+23  Answer:  973 
☑ Guess:  973 

--------------------------------------------------
Iteration 2
Train on 45000 samples, validate on 5000 samples
Epoch 1/1
45000/45000 [==============================] - 6s 142us/step - loss: 0.0153 - acc: 0.9986 - val_loss: 0.0344 - val_acc: 0.9902
Question:  48+860  Answer:  908 
☑ Guess:  908 
Question:  170+277 Answer:  447 
☑ Guess:  447 
Question:  826+7   Answer:  833 
☑ Guess:  833 
Question:  45+154  Answer:  199 
☒ Guess:  299 
Question:  15+48   Answer:  63  
☑ Guess:  63  

-------------------

KeyboardInterrupt: ignored

Check Five digits reversed:
+ One layer LSTM (128 HN), 550k training examples = 99% train/test accuracy in 30 epochs